data_perpus/urls.py
# import modul yang dibutuhkan
from django.conf.urls import url
from django.urls import path

# import views untuk ditampilkan
from . import views
from .models import Siswa
app_name = 'buku'

urlpatterns = [
    path('tambah-bahasa-buku/', views.BahasaBukuCreateView.as_view(),name='tambah-bahasa-buku'),
    path('tambah-genre/', views.GenreCreateView.as_view(),name='tambah-genre'),
    path('delete-pinjam-buku/<int:pk>', views.PinjamDeleteView.as_view(), name='pinjam-delete'),
    path('update-pinjam-buku/<int:pk>', views.PinjamUpdateView.as_view(),name='pinjam-update'),
    path('pinjam-buku/', views.PinjamCreateView.as_view(), name='pinjam-buku'),
    path('list-pinjam/', views.PinjamListView.as_view(), name='list-pinjam'),
    path('delete-siswa/<int:pk>', views.SiswaDeteteView.as_view(),name='delete-siswa'),
    path('update-siswa/<int:pk>', views.SiswaUpdateView.as_view(), name='update-siswa'),
    path('tambah-siswa/', views.SiswaCreateView.as_view(),name='tambah-siswa'),
    path('detail-siswa/<int:pk>', views.SiswaDetailView.as_view(), name='detail-siswa'),
    path('list-siswa', views.SiswaListView.as_view(),name='list-siswa'),
    path('delete-buku/<int:pk>/', views.BookDeleteView.as_view(),name='delete-buku'),
    path('update-buku/<int:pk>/', views.BookUpdateView.as_view(),name='update-buku'),
    path('tambah-buku/', views.BookCreateView.as_view(), name='tambah-buku'),
    path('detail-buku/<slug:slug>', views.BookDetailView.as_view(), name='detail-buku'),
    path('', views.BookListView.as_view(), name='list'),
]

perpustakaan_sekolah/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# import view buat nampilin HomeView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('buku/', include('data_perpus.urls', namespace='buku')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.HomeView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/navbar.html
<div class="container-fluid">
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-success">
    <a href="/" class="navbar-brand">Perpustakaan SMK Walisongo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href="{% url "buku:list" %}" class="nav-link">Daftar Buku</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'buku:list-siswa' %}" class="nav-link">Daftar Siswa</a>
        </li>

        {% if user.is_superuser %}
        {# untuk menambah daftar anggota/siswa yang mau pinjam buku #}
          <li class="nav-item">
            <a href="{% url 'buku:tambah-siswa' %}" class="nav-link">Tambah Siswa</a>
          </li>

          {# untuk menambah buku #}
          <li class="nav-item">
            <a href="{% url 'buku:tambah-buku' %}" class="nav-link">Tambah Buku</a>
          </li>

          {# menampilkan pinjam buku #}
          <li class="nav-item">
            <a href="{% url 'buku:pinjam-buku' %}" class="nav-link">Pinjam Buku</a>
          </li>

          <li class="nav-item">
            <a href="{% url 'buku:list-pinjam' %}" class="nav-link">Daftar Peminjam</a>
          </li>
        {% endif %}

        {% if user.is_authenticated %}
          <div class="dropdown float">
            <a href="" class="dropdown-toggle text-white" data-toggle="dropdown">Halo, {{request.user}}</a>
            <div class="dropdown-menu">
              <a href="#" class="dropdown-item">Reset Password</a> {# Reset Password #}
              <a href="{% url "admin:index" %}" class="dropdown-item">Panel Admin</a>
              <a href="{% url 'logout' %}" class="dropdown-item">Logout</a> {# Logout #}
            </div>
          </div>
          {% else %}
            <li class="nav-item">
              <a href="{% url "login" %}" class="nav-link">Login</a>
            </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</div>