data_perpus/urls.py
# import modul yang dibutuhkan
from django.conf.urls import url
from django.urls import path

# import views untuk ditampilkan
from . import views
from .models import Siswa
app_name = 'buku'

urlpatterns = [
    path('tambah-bahasa-buku/', views.BahasaBukuCreateView.as_view(),name='tambah-bahasa-buku'),
    path('tambah-genre/', views.GenreCreateView.as_view(),name='tambah-genre'),
    path('delete-pinjam-buku/<int:pk>', views.PinjamDeleteView.as_view(), name='pinjam-delete'),
    path('update-pinjam-buku/<int:pk>', views.PinjamUpdateView.as_view(),name='pinjam-update'),
    path('pinjam-buku/', views.PinjamCreateView.as_view(), name='pinjam-buku'),
    path('list-pinjam/', views.PinjamListView.as_view(), name='list-pinjam'),
    path('delete-siswa/<int:pk>', views.SiswaDeteteView.as_view(),name='delete-siswa'),
    path('update-siswa/<int:pk>', views.SiswaUpdateView.as_view(), name='update-siswa'),
    path('tambah-siswa/', views.SiswaCreateView.as_view(),name='tambah-siswa'),
    path('detail-siswa/<int:pk>', views.SiswaDetailView.as_view(), name='detail-siswa'),
    path('list-siswa', views.SiswaListView.as_view(),name='list-siswa'),
    path('delete-buku/<int:pk>/', views.BookDeleteView.as_view(),name='delete-buku'),
    path('update-buku/<int:pk>/', views.BookUpdateView.as_view(),name='update-buku'),
    path('tambah-buku/', views.BookCreateView.as_view(), name='tambah-buku'),
    path('detail-buku/<slug:slug>', views.BookDetailView.as_view(), name='detail-buku'),
    path('', views.BookListView.as_view(), name='list'),
]

perpustakaan_sekolah/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# import view buat nampilin HomeView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('buku/', include('data_perpus.urls', namespace='buku')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.HomeView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load  static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "vendor/bootsrap/css/bootstrap.min.css" %}">

    <title>
      {% block page_title %}

      {% endblock page_title %}
    </title>
  </head>
  <body>
    {% include "partials/navbar.html" %}
    {% block contents %}

    {% endblock contents %}

    
    <!-- Optional JavaScript -->
    <script src="{% static "vendor/jquery/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "vendor/popper/popper.min.js" %}"></script>
    <script src="{% static "vendor/bootsrap/js/bootstrap.min.js" %}"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}
{{title}}
{% endblock page_title %}

{% block contents %}
{# awal bagian style #}
  <style media="screen">
  /* import font */
    @import url('static/assets/Quicksand-VariableFont_wght.ttf');
    @import url('static/assets/fonts/RobotoSlab-VariableFont_wght.ttf');

    h1 {
      font-family: 'Roboto Slab';
    }

    .jumbotron {
      background-image: url(static/assets/img/background.jpg);
      background-size: cover;
      background-repeat: no-repeat;
      height: 100%;
      width: 100%
    }

    .navbar {
      margin-bottom: 0px;
    }

    p {
      font-family: 'Quicksand';
    }
  </style>
      <div class="jumbotron jumbotron-fluid">
        <img src="static/assets/img/smk.png" alt="{{judul}}" class="rounded mx-auto d-block">
        <h1 class="display-4 text-white">Perpustakaan Digital SMK Walisongo Pecangaan</h1>
        <p class="lead text-white text-center">{{title}}</p>
      </div>

      <div class="card">
        <div class="card-header">Note:</div>
        <div class="card-body">
          <h5 class="card-title">Attention</h5>
          <p class="card-text">Tambah Bahasa dan Genre Buku Dahulu Sebelum Menambah Buku</p>
          <a href="{% url 'buku:tambah-bahasa-buku' %}" class="btn btn-outline-primary btn-lg">Tambah Bahasa Buku</a>
          <a href="{% url 'buku:tambah-genre' %}" class="btn btn-outline-success btn-lg">Tambah Genre Buku</a>
        </div>
      </div>
{% endblock contents %}