data_perpus/urls.py
# import modul yang dibutuhkan
from django.conf.urls import url
from django.urls import path

# import views untuk ditampilkan
from . import views
from .models import Siswa
app_name = 'buku'

urlpatterns = [
    path('tambah-bahasa-buku/', views.BahasaBukuCreateView.as_view(),name='tambah-bahasa-buku'),
    path('tambah-genre/', views.GenreCreateView.as_view(),name='tambah-genre'),
    path('delete-pinjam-buku/<int:pk>', views.PinjamDeleteView.as_view(), name='pinjam-delete'),
    path('update-pinjam-buku/<int:pk>', views.PinjamUpdateView.as_view(),name='pinjam-update'),
    path('pinjam-buku/', views.PinjamCreateView.as_view(), name='pinjam-buku'),
    path('list-pinjam/', views.PinjamListView.as_view(), name='list-pinjam'),
    path('delete-siswa/<int:pk>', views.SiswaDeteteView.as_view(),name='delete-siswa'),
    path('update-siswa/<int:pk>', views.SiswaUpdateView.as_view(), name='update-siswa'),
    path('tambah-siswa/', views.SiswaCreateView.as_view(),name='tambah-siswa'),
    path('detail-siswa/<int:pk>', views.SiswaDetailView.as_view(), name='detail-siswa'),
    path('list-siswa', views.SiswaListView.as_view(),name='list-siswa'),
    path('delete-buku/<int:pk>/', views.BookDeleteView.as_view(),name='delete-buku'),
    path('update-buku/<int:pk>/', views.BookUpdateView.as_view(),name='update-buku'),
    path('tambah-buku/', views.BookCreateView.as_view(), name='tambah-buku'),
    path('detail-buku/<slug:slug>', views.BookDetailView.as_view(), name='detail-buku'),
    path('', views.BookListView.as_view(), name='list'),
]

perpustakaan_sekolah/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# import view buat nampilin HomeView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('buku/', include('data_perpus.urls', namespace='buku')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.HomeView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_perpus/models.py
# import modul yang dibutuhkan
from django.db import models
from django.contrib.auth.models import User # digunakan untuk import User
from django.urls import reverse # digunakan untuk meng-generate url dengan reverse URLpatterns
from django.db.models.signals import post_save
from django.utils.text import slugify
# Create your models here.

# relasi database untuk mengatur genre buku
class Genre(models.Model):
    genre = models.CharField(max_length=200, help_text="Masukan Genre Buku, (Misalnya: Kesehatan, Sains, Teknologi)")

    def get_absolute_url(self):
        return reverse('index')
    # mengembalikan nilai string dan dikembalikan dengan object menggunakan __str__
    def __str__(self):
        return self.genre

# relasi database untuk memanagemen bahasa buku yang akan dipinjam
class BahasaBuku(models.Model):
    bahasa = models.CharField(max_length=200, help_text="Masukan Bahasa Buku (misalnya: Bahasa Indonesia, English, Jepang)")

    def get_absolute_url(self):
        return reverse('index')

    def __str__(self):
        return self.bahasa

# relasi buku akan mempunyai 2 foreign key yaitu author
# relasi buku dapat menampung genre jadi menggunakan manytomany field
class Buku(models.Model):
    judul = models.CharField(max_length=200)
    author = models.CharField(max_length=150)
    slug = models.SlugField(max_length=255,unique=True, editable=False)
    deskripsi = models.TextField(help_text="Masukan Deskripsi Buku")
    isbn = models.CharField(max_length=13, help_text='13 Karakter <a href="https://www.isbn-international.org/content/what-isbn">Nomor ISBN</a>')
    genre = models.ManyToManyField(Genre, help_text="Apa Genre untuk Buku ini")
    bahasa = models.ForeignKey('BahasaBuku', on_delete=models.SET_NULL, null=True)
    total_copies = models.IntegerField()
    available_copies = models.IntegerField()
    gambar = models.ImageField(blank=True, null=True, upload_to='gambar_buku/')

    @property
    def get_gambar_url(self):
        if self.gambar and hasattr(self.gambar, 'url'):
            return self.gambar.url
        else:
            return "/media/assets/no-pic.png"

    def save(self):
        self.slug = slugify(self.judul)
        super(Buku, self).save()

    def get_absolute_url(self):
        url_slug = {
            'slug':self.slug,
        }

        return reverse('buku:detail-buku', kwargs=url_slug)


    def __str__(self):
        return self.judul


# relasi database Siswa digunakan untuk menampung info tentang Siswa yang meminjam buku di perpus
# fungsi nisn digunakan untuk mengidentifikasi siswa secara unik
class Siswa(models.Model):
    CHOICES_JURUSAN = (
        ('Teknik Komputer Jaringan', 'Teknik Komputer Jaringan'),
        ('Teknik Kendaraan Ringan', 'Teknik Kendaraan Ringan'),
        ('Kriya Tekstil', 'Kriya Tekstil'),
        ("Perbankan Syari'ah", "Perbankan Syari'ah"),
    )

    CHOICES_KELAS = (
        ('X', 'X'),
        ('XI', 'XI'),
        ('XII', 'XII'),
    )


    nisn = models.CharField(max_length=10, unique=True)
    nama = models.CharField(max_length=100)
    kelas = models.CharField(max_length=3, choices=CHOICES_KELAS, default='x')
    jurusan = models.CharField(max_length=100, choices=CHOICES_JURUSAN, default='tkj')
    nomor_telp = models.CharField(max_length=14)
    total_buku = models.IntegerField(default=0)
    email = models.EmailField(unique=True)
    foto = models.ImageField(blank=True, upload_to='foto_profile')

    def get_absolute_url(self):
        url_id = {
            'url_id': self.id,
            }
        return reverse('buku:list-siswa')


    def __str__(self):
        return str(self.nama)


# relasi digunakan untuk menginfo kan tentang buku yang dipinjam
# ForeignKey buku dan siswa untuk mereferensi buku dan Siswa
# fungsi roll_no digunakan untuk identifikasi Siswa
# jika buku dikembalikan maka akan data pinjaman akan dihapus dari database

class PinjamBuku(models.Model):
    siswa = models.ForeignKey('Siswa', on_delete=models.CASCADE)
    buku = models.ForeignKey('Buku', on_delete=models.CASCADE)
    awal_pinjam = models.DateTimeField(null=True, blank=True, help_text="Format Tanggal: tahun-bulan-tanggal, contoh:2020-05-03")
    tgl_kembali = models.DateTimeField(null=True, blank=True, help_text="Format Tanggal: tahun-bulan-tanggal, contoh:2020-05-03")

    def get_absolute_url(self):
        return reverse('buku:list-pinjam')

    def __str__(self):
        return self.siswa.nama+" telah meminjam "+self.buku.judul

data_perpus/forms.py
# import logging
from django import forms
from .models import *
# import app timepicker
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker

class GenreBukuForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'
        exclude = ()

class BahasaBukuForm(forms.ModelForm):
    class Meta:
        model = BahasaBuku
        fields = '__all__'
        exclude = ()

class FormBuku(forms.ModelForm):
    class Meta:
        model = Buku
        fields = '__all__'
        exclude = ()


    # def save(self, *args, **kwargs):
    #     logger = logging.getLogger(__name__)
    #     logger.info(self.gambar)
    #     return super(FormBuku, self).save(*args, **kwargs)

    # def clean(self):
    #     cleaned_data = super().clean()
    #     gambar = cleaned_data.get('gambar')
    #     logger = logging.getLogger(__name__)
    #     logger.info(gambar)
    #     return cleaned_data

class FormPinjamBuku(forms.ModelForm):
    class Meta:
        model = PinjamBuku
        fields = [
            'siswa',
            'buku',
            'awal_pinjam',
            'tgl_kembali',
        ]



class FormSiswa(forms.ModelForm):
    class Meta:
        model = Siswa
        fields = '__all__'

data_perpus/views.py
# modul utama yang dibutuhkan
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy

# modul untuk menginclude metod decorator pada class
from django.utils.decorators import method_decorator

# modul autentifikasi decorator
from django.contrib.auth.decorators import login_required

# model untuk menentukan waktu
import datetime

# modul untuk template
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

# modul untuk kebutuhan relasi database dan forms untuk ditampilkan
from .models import *
from . forms import *


# class Buku
class BookListView(ListView):
    model = Buku
    template_name = "data_perpus/buku_list.html"
    # context_object_name = 'book_list'

    extra_context = {
        'title':'Semua Buku',
    }

    def get_context_data(self, *args, **kwargs):
        self.kwargs.update(self.extra_context)
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)

# class ini digunakan untuk menampilkan isi dari buku
class BookDetailView(DetailView):
    model = Buku
    template_name = "data_perpus/buku_detail.html"


# class ini digunakan untuk Tambah Buku menggunakan createView
@method_decorator(login_required, name='dispatch')
class BookCreateView(CreateView):
    form_class = FormBuku
    template_name = 'data_perpus/tambah-buku.html'
    extra_context = {
        'judul': 'Tambah Buku',
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)

method_decorator(login_required, name='dispatch')
class BookUpdateView(UpdateView):
    form_class = FormBuku
    model = Buku
    template_name = 'data_perpus/tambah-buku.html'
    extra_context = {
        'judul':'Update Buku'
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)


method_decorator(login_required, name='dispatch')
class BookDeleteView(DeleteView):
    model = Buku
    success_url = reverse_lazy('buku:list')


# class Siswa
class SiswaListView(ListView):
    model = Siswa
    template_name = 'data_perpus/list_siswa.html'
    context_object_name = 'siswa_list'
    extra_context = {
        'title':'Daftar Siswa Anggota Perpus',
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)

method_decorator(login_required, name='dispatch')
class SiswaDetailView(DetailView):
    model = Siswa
    template_name = 'data_perpus/siswa_detail.html'

method_decorator(login_required, name='dispatch')
class SiswaCreateView(CreateView):
    form_class = FormSiswa
    template_name = 'data_perpus/tambah-buku.html'
    extra_context = {
        'judul': 'Tambah Siswa Baru'
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)

method_decorator(login_required, name='dispatch')
class SiswaUpdateView(UpdateView):
    form_class = FormSiswa
    model = Siswa
    template_name = 'data_perpus/tambah-buku.html'
    extra_context = {
        'judul': 'Update Profil Anggota',
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)

method_decorator(login_required, name='dispatch')
class SiswaDeteteView(DeleteView):
    model = Siswa
    success_url = reverse_lazy('buku:list-siswa')


# class Pinjam buku

# class ini digunakan untuk menampilkan siswa yang telah meminjam buku
method_decorator(login_required, name='dispatch')
class PinjamListView(ListView):
    model = PinjamBuku
    template_name = 'data_perpus/list-pinjam.html'
    context_object_name = 'pinjam_buku_list'
    extra_context = {
        'judul':'Daftar Siswa yang Meminjam Buku'
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)

# class ini digunakan untuk meminjam buku
method_decorator(login_required, name='dispatch')
class PinjamCreateView(CreateView):
    form_class = FormPinjamBuku
    model = PinjamBuku
    template_name = 'data_perpus/pinjam-buku.html'
    extra_context = {
        'judul':'Pinjam Buku',
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)

# class Ini digunakan untuk update siswa yang telah meminjam buku
method_decorator(login_required, name='dispatch')
class PinjamUpdateView(UpdateView):
    form_class = FormPinjamBuku
    model = PinjamBuku
    template_name = 'data_perpus/pinjam-buku.html'
    extra_context = {
        'judul':'Update Siswa yang Meminjam Buku',
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)


method_decorator(login_required, name='dispatch')
class PinjamDeleteView(DeleteView):
    model = PinjamBuku
    success_url = reverse_lazy('buku:list-pinjam')


# Class Untuk menambahkan genre
method_decorator(login_required, name='dispatch')
class GenreCreateView(CreateView):
    form_class = GenreBukuForm
    model = Genre
    template_name = 'data_perpus/partials/create_gen.html'
    extra_context = {
        'judul':'Tambah Genre Buku',
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)

# class Untuk menambah bahasa buku
method_decorator(login_required, name='dispatch')
class BahasaBukuCreateView(CreateView):
    form_class = BahasaBukuForm
    model = BahasaBuku
    template_name = 'data_perpus/partials/create_gen.html'
    extra_context = {
        'judul':'Tambah Bahasa Buku',
    }

    def get_context_data(self, *args, **kwargs):
        kwargs.update(self.extra_context)
        return super().get_context_data(*args, **kwargs)

data_perpus/templates/data_perpus/buku_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hapus Buku</title>
    <link rel="stylesheet" href="{% static "vendor/bootsrap/css/bootstrap.min.css" %}">
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="card">
          <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div class="card-body">
              <p class="card-title">Hapus Buku {{object}}</p>
              <input class="btn btn-danger" type="submit" value="Ya">
              <a href="{% url 'buku:list' %}" class="btn btn-success">Tidak</a>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script src="{% static "vendor/jquery/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "vendor/popper/popper.min.js" %}"></script>
    <script src="{% static "vendor/bootsrap/js/bootstrap.min.js" %}"></script>
  </body>
</html>

data_perpus/templates/data_perpus/buku_detail.html
{% extends "base.html" %}

{% block page_title %}
  Lihat: {{buku.judul}}
{% endblock page_title %}


{% block contents %}
<div class="container" style="margin-top:80px;">
  <div class="card">
    <div class="row no-gutters">
      <div class="col-md-4">
        {% if buku.get_gambar_url %}
        <img src="{{buku.get_gambar_url|default_if_none:'#'}}" alt="{{buku.slug}}" class="card-img">
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h4 class="card-text">Judul: {{buku.judul}}</h4>
          <h4 class="card-text">Penyusun: {{buku.author}}</h4>
          <h4 class="card-text">Bahasa Buku: {{buku.bahasa}}</h4>
          <h4 class="card-text">ISBN: {{buku.isbn}}</h4>
            {% for genre in buku.genre.all %}
              <h4 class="card-text">Genre Buku: {{genre}}</h4>
              {% if not forloop.last %}

              {% endif %}

            {% endfor %}

          <h4 class="card-text">Deskripsi Buku: {{buku.deskripsi}}</h4>
          <h4 class="card-text">Buku Yang Tersedia: {{buku.available_copies}}</h4>
          <h4 class="card-text">Jumlah Total Buku: {{buku.total_copies}}</h4>

          {% if user.is_superuser %}
              <a href="{% url 'buku:delete-buku' buku.pk %}" class="btn btn-danger">Hapus Buku</a>
              <a href="{% url 'buku:update-buku' buku.pk %}" class="btn btn-success">Update Buku</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock contents %}

data_perpus/templates/data_perpus/buku_list.html
{# template untuk menampilkan buku yang ada di perpus #}
{% extends "base.html" %}

{% block page_title %}
  {{title}}
{% endblock page_title %}

{% block contents %}
{% if buku_list %}

<style media="screen">
/* bagian CSS */
  .container {
    margin-top: 80px;
  }

  .card {
    width: 24rem;
  }

  .card-img-top {
    max-height:300px;width: 100%;
    object-fit:cover;
    object-position:center
  }
</style>
  <div class="container">
    <div class="row">
      {% for buku in object_list %}
        <div class="col-sm-6">
          <div class="card">
            <img src="{{buku.get_gambar_url|default_if_none:'#'}}" alt="buku.slug" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title">{{buku.judul}}</h5>
              <h6 class="card-subtitle mb-2 text-muted">Penyusun: {{buku.author}}</h6>
              <p class="card-text">{{buku.summary|truncatewords:10}}</p>
              <a href="{% url 'buku:detail-buku' buku.slug %}" class="btn btn-primary">Lihat Buku</a>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
  </div>
  {% else %}
  <h1 class=" display-4 text-center" style="margin-top:300px;">Daftar Buku Kosong</h1>
  {% endif %}
{% endblock contents %}

data_perpus/templates/data_perpus/list-pinjam.html
{% extends "base.html" %}

{% block page_title %}
  {{judul}}
{% endblock page_title %}

{% block contents %}
  <div class="container" style="margin-top:80px;">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th scope="col">No.</th>
          <th scope="col">Nama Siswa</th>
          <th scope="col">Buku Yang Dipinjam</th>
          <th scope="col">Awal Pinjam</th>
          <th scope="col">Tanggal Kembali</th>
          {% if user.is_superuser %}
          <th scope="col">Opsi</th>
          <th scope="col"></th>
          {% endif %}

        </tr>
      </thead>
      <tbody>
        {% for pinjam in pinjam_buku_list %}
          <td>{{forloop.counter}}</td>
          <td>{{pinjam.siswa.nama}}</td>
          <td>{{pinjam.buku.judul}}</td>
          <td>{{pinjam.awal_pinjam}}</td>
          <td>{{pinjam.tgl_kembali}}</td>

          {% if user.is_superuser %}
            <td><a href="{% url 'buku:pinjam-update' pinjam.pk %}" class="btn btn-success">Ubah Data</a></td>
            <td><a href="{% url 'buku:pinjam-delete' pinjam.pk %}" class="btn btn-danger">Hapus Data</a></td>
          {% endif %}
        {% endfor %}

      </tbody>
    </table>
  </div>
{% endblock contents %}

data_perpus/templates/data_perpus/list_siswa.html
{% extends "base.html" %}

{% block page_title %}
{{title}}
{% endblock page_title %}

{% block contents %}
  <div class="container" style="margin-top:80px;">
    <table class="table table-striped mt-3">
      <thead class="thead-dark">
        <tr>
          <th scope="col">No.</th>
          <th scope="col">NISN</th>
          <th scope="col">Nama</th>
          <th scope="col">Kelas</th>
          <th scope="col">Jurusan</th>
          <th scope="col">No Telp</th>
          <th scope="col">Total Buku</th>
          <th scope="col">E-mail</th>
          <th scope="col">Info Lengkap</th>
        </tr>
      </thead>
      <tbody>
        {% for siswa in siswa_list %}
          <td>{{forloop.counter}}</td>
          <td>{{siswa.nisn}}</td>
          <td>{{siswa.nama}}</td>
          <td>{{siswa.kelas}}</td>
          <td>{{siswa.jurusan}}</td>
          <td>{{siswa.nomor_telp}}</td>
          <td>{{siswa.total_buku}}</td>
          <td>{{siswa.email}}</td>
          <td><a href="{% url 'buku:detail-siswa' siswa.pk %}" class="btn btn-primary">Detail Siswa</a></td>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock contents %}

data_perpus/templates/data_perpus/pinjam-buku.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}
  {{judul}}
{% endblock page_title %}

{% block contents %}
<div class="container" style="margin-top:80px;">
  <form enctype="multipart/form-data" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <button class="btn btn-primary">Pinjam Buku</button>
  </form>
</div>
{% endblock contents %}

data_perpus/templates/data_perpus/pinjambuku_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hapus Data Peminjaman</title>
    <link rel="stylesheet" href="{% static "vendor/bootsrap/css/bootstrap.min.css" %}">
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="card">
          <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div class="card-body">
              <p class="card-title">Hapus Data {{object}}</p>
              <input class="btn btn-danger" type="submit" value="Ya">
              <a href="{% url 'buku:list' %}" class="btn btn-success">Tidak</a>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script src="{% static "vendor/jquery/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "vendor/popper/popper.min.js" %}"></script>
    <script src="{% static "vendor/bootsrap/js/bootstrap.min.js" %}"></script>
  </body>
</html>

data_perpus/templates/data_perpus/siswa_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hapus Siswa</title>
    <link rel="stylesheet" href="{% static "vendor/bootsrap/css/bootstrap.min.css" %}">
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="card">
          <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div class="card-body">
              <p class="card-title">Hapus Siswa {{object}}</p>
              <input class="btn btn-danger" type="submit" value="Ya">
              <a href="{% url 'buku:list' %}" class="btn btn-success">Tidak</a>
            </div>
          </form>
        </div>
      </div>
    </div>
    <script src="{% static "vendor/jquery/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "vendor/popper/popper.min.js" %}"></script>
    <script src="{% static "vendor/bootsrap/js/bootstrap.min.js" %}"></script>
  </body>
</html>

data_perpus/templates/data_perpus/siswa_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> Lihat: {{siswa.nama}}</title>
    <link rel="stylesheet" href="{% static "vendor/bootsrap/css/bootstrap.min.css" %}">
  </head>
  <body>
    <div class="container" style="margin-top:30px;">
      <div class="card">
        <div class="row no-gutters">
          <div class="col-md-4">
            <img src="{{siswa.foto.url}}" alt="{{siswa.nama}}" class="card-img-top">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h4 class="card-title">Kartu Anggota Perpustakaan SMK Walisongo</h4>
              <p class="card-text">Nama: {{siswa.nama}}</p>
              <p class="card-text">Kelas: {{siswa.kelas}}</p>
              <p class="card-text">Jurusan: {{siswa.jurusan}}</p>
              <p class="card-text">Kontak: {{siswa.nomor_telp}}</p>
              <p class="card-text text-muted">Buku yang Dipinjam: {{siswa.total_buku}}</p>
              {% if user.is_superuser %}
                  <a href="{% url 'buku:update-siswa' siswa.pk %}" class="btn btn-success">Ubah Profile</a>
                  <a href="{% url 'buku:delete-siswa' siswa.pk %}" class="btn btn-danger">Hapus Profile</a>
                  <br><br>
              {% endif %}
              <div class="card-footer">
                <small class="text-muted">Kartu Perpus <a href="https://smkw9jepara.sch.id">SMK Walisongo Pecangaan</a></small>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
    <script src="{% static "vendor/jquery/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "vendor/popper/popper.min.js" %}"></script>
    <script src="{% static "vendor/bootsrap/js/bootstrap.min.js" %}"></script>
  </body>
</html>

data_perpus/templates/data_perpus/tambah-buku.html
{# template sementara #}
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block page_title %}
  {{judul}}
{% endblock page_title %}

{% block contents %}
  <div class="container" style="margin-top: 75px;">
    <div class="row">
      <div class="form-group">
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{form |crispy}}
          <button type="submit" class="btn btn-primary">{{judul}}</button>
        </form>
      </div>
    </div>
  </div>
{% endblock contents %}